[workspace]
members = ["host", "methods", "lib"]
resolver = "2"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[workspace.package]
edition = "2024"

[workspace.dependencies]
alloy-primitives = "0.8"
ethereum_ssz = "0.8.2"
serde = { version = '1.0', features = ['derive', "rc"] }
ssz_rs = { git = "https://github.com/unnawut/ssz-rs.git", branch = "partial_merkle_tree", package = "ssz_rs" } # Efficient merkle tree
ssz_rs_derive = { git = "https://github.com/ralexstokes/ssz-rs.git", package = "ssz_rs_derive" }
tracing = "0.1.40"
tree_hash = "0.9"
typenum = "1.12.0"

# Ream crates
ream-consensus = { git = "https://github.com/ReamLabs/ream", package = "ream-consensus" }
ream-bls = { git = "https://github.com/ReamLabs/ream.git", package = "ream-bls" }

# Internal crates
consensus-beacon-state = { path = "consensus/beacon-state" }
consensus-common = { path = "consensus/common" }

[patch.crates-io]
ethereum_hashing = { git = "https://github.com/ReamLabs/ethereum_hashing" }
