name: Build Guest

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.85.0

      - name: Install Risc0 toolchain
        run: |
          curl -L https://risczero.com/install | bash
          /home/runner/.risc0/bin/rzup install rust 1.85.0
          /home/runner/.risc0/bin/rzup install r0vm 2.0.1
          /home/runner/.risc0/bin/rzup install cargo-risczero 2.0.1

      - name: Build Risc0 guest program
        run: |
          cargo build
