name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [ "master" ]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run rustfmt
      run: cargo fmt -- --check

  cargo-clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Clippy
      run: |
        cargo clippy --all --all-targets --no-deps -- --deny warnings # clippy for ream, default features

  cargo-sort:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install cargo sort
      run: cargo install cargo-sort

    - name: Run cargo sort
      run: cargo sort --grouped --check

  build:
    runs-on: ubuntu-latest
    needs: [cargo-fmt, cargo-clippy]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.85.0

      - name: Install Risc0 toolchain
        run: |
          curl -L https://risczero.com/install | bash
          /home/runner/.risc0/bin/rzup install rust 1.85.0
          /home/runner/.risc0/bin/rzup install r0vm 2.0.1
          /home/runner/.risc0/bin/rzup install cargo-risczero 2.0.1

      - name: Build Risc0 guest program
        run: |
          cargo build
